#!/bin/bash -eu

set -euo pipefail

case "$1" in
  build|coverage|query|cquery|fetch|mobile-install|print_action|run|test)
    "$BAZEL_REAL" run @bazel_gazelle//cmd/autogazelle -- -gazelle=//:gazelle
    ;;
esac

exec "$BAZEL_REAL" "$@"
